name: Deploy to live server
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy code to server
      uses: appleboy/scp-action@master
      with:
        host: 191.96.31.250
        username: root
        password: Amoltheking123**
        source: "./*"
        target: "/var/www/portfolio/"
