name: Deploy to live server
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clone repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo rm -rf /root/portfolio/my-app
            git clone https://github.com/amehta0104/Amol-React-Portfolio.git /root/portfolio/
      - name: Delete existing files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
           cd /root/portfolio/
           sudo apt install nodejs
           sudo apt install npm
           cd /root/portfolio/my-app/
           sudo npm i
           sudo npm run build
           sudo rm -rf /var/www/portfolio/my-app
           sudo mkdir /var/www/portfolio/my-app
           sudo cp -r build/* /var/www/portfolio/my-app
           cd /var/www/portfolio
           sudo systemctl reload nginx
           
